"""Generate LaTeX macros for atlas.tex from the latest data.

Reads the cached parquet files, computes every statistic that appears in
the manuscript prose, and writes them to atlas_macros.tex.

Usage:
    python generate_macros.py
"""

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import pearsonr

sys.path.insert(0, str(Path(__file__).resolve().parent))
from atlas_common import AXIS_COLS, BOUNDARIES_PATH, OCTANT_ORDER, classify_octants, load_all_cached, load_hq_fids

# ── Column definitions ──
SVC_COLS = {
    "trees": "cc_trees_nearest_max_1600",
    "green": "cc_green_nearest_max_1600",
    "retail": "cc_retail_nearest_max_1600",
    "business": "cc_business_and_services_nearest_max_1600",
    "eat_drink": "cc_eat_and_drink_nearest_max_1600",
    "health": "cc_health_and_medical_nearest_max_1600",
    "education": "cc_education_nearest_max_1600",
    "transport": "cc_transport_nearest_max_1600",
    "accommodation": "cc_accommodation_nearest_max_1600",
    "arts": "cc_arts_and_entertainment_nearest_max_1600",
    "attractions": "cc_attractions_and_activities_nearest_max_1600",
    "religious": "cc_religious_nearest_max_1600",
}

MORPH_COLS = {
    "height": "cc_mean_height_median_400_wt",
    "height_var": "cc_mean_height_mad_400_wt",
    "volume": "cc_volume_median_400_wt",
    "area": "cc_area_median_400_wt",
    "perimeter": "cc_perimeter_median_400_wt",
    "compactness": "cc_compactness_median_400_wt",
    "corners": "cc_corners_median_400_wt",
    "swr": "cc_shared_wall_ratio_median_400_wt",
    "frontage": "frontage_max",
    "gsi": "cc_block_covered_ratio_median_400_wt",
    "fsi": "cc_block_far_median_400_wt",
    "osr": "cc_block_osr_median_400_wt",
    "mean_floors": "cc_block_l_median_400_wt",
    "block_mean_ht": "cc_block_mean_height_median_400_wt",
    "block_perim": "cc_block_perimeter_median_400_wt",
    "orientation": "cc_orientation_mad_400_wt",
    "bldg_count": "cc_building_400_nw",
    "block_count": "cc_block_400_nw",
}

DEMO_COLS = {
    "density": "density",
    "employment": "emp_%",
    "youth": "y_lt15_%",
    "working_age": "y_1564_%",
    "elderly": "y_ge65_%",
}

CENTRALITY_COLS = {
    "closeness_800": "cc_beta_800",
    "density_800": "cc_density_800",
    "density_400": "cc_density_400",
}

OUTPUT_DIR = Path(__file__).resolve().parent.parent / "outputs" / "atlas"
MACRO_FILE = Path(__file__).resolve().parent.parent / "atlas_macros.tex"


class MacroWriter:
    """Collect LaTeX macro definitions and write them to a file."""

    def __init__(self):
        self.macros: dict[str, str] = {}
        self.sections: list[tuple[str, list[str]]] = []
        self._current_section: str = ""
        self._current_keys: list[str] = []

    def section(self, name: str):
        if self._current_section:
            self.sections.append((self._current_section, self._current_keys))
        self._current_section = name
        self._current_keys = []

    def add(self, name: str, value, fmt: str = ""):
        """Add a macro. fmt is a Python format spec, e.g. '.0f', '.1f', '.3f'."""
        if isinstance(value, (int, np.integer)):
            text = f"{value:,}"
        elif isinstance(value, (float, np.floating)):
            text = f"{value:{fmt}}" if fmt else f"{value}"
        else:
            text = str(value)
        self.macros[name] = text
        self._current_keys.append(name)

    def write(self, path: Path):
        # Flush last section
        if self._current_section:
            self.sections.append((self._current_section, self._current_keys))

        lines = [
            "% Auto-generated by generate_macros.py — do not edit by hand.",
            "% Re-run: cd paper_research/code && python generate_macros.py",
            "",
        ]
        for section_name, keys in self.sections:
            lines.append(f"% {'─' * 60}")
            lines.append(f"% {section_name}")
            lines.append(f"% {'─' * 60}")
            for k in keys:
                v = self.macros[k]
                lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
            lines.append("")

        path.write_text("\n".join(lines) + "\n")
        print(f"Wrote {len(self.macros)} macros to {path}")


def main():
    mw = MacroWriter()

    # ══════════════════════════════════════════════════════════════════
    # Load data
    # ══════════════════════════════════════════════════════════════════
    from shared_config import MORPH_COLS as MORPH_COLS_LIST

    all_cols = (
        list(AXIS_COLS.values())
        + list(SVC_COLS.values())
        + list(MORPH_COLS.values())
        + list(DEMO_COLS.values())
        + list(CENTRALITY_COLS.values())
        + MORPH_COLS_LIST  # 400m morphometric columns for eta-squared / PCA
    )
    print("Loading data …")
    df = load_all_cached(columns=all_cols)
    n_total = len(df)
    n_cities = df["bounds_fid"].nunique()
    print(f"  {n_total:,} streets across {n_cities} cities")

    classified, thresholds = classify_octants(df)
    n_classified = len(classified)
    pct_classified = 100 * n_classified / n_total
    pct_excluded = 100 - pct_classified

    # Load boundaries for city metadata
    import geopandas as gpd

    bounds = gpd.read_file(BOUNDARIES_PATH).to_crs(3035)
    n_countries = bounds["country"].nunique()
    label_map = bounds.set_index("bounds_fid")["label"].to_dict()

    def city_fids(names):
        """Resolve city names to bounds_fids, tolerating composite labels.

        Matches an exact label first, then a composite label such as
        "Rotterdam [The Hague]". Substring matching is deliberately avoided
        (e.g. "Madrid" must not match "Rivas-Vaciamadrid").
        """
        fids = []
        for name in names:
            matches = bounds[bounds["label"] == name]
            if len(matches) == 0:
                matches = bounds[bounds["label"].str.startswith(f"{name} [")]
            if len(matches) == 0:
                print(f"  WARNING: no boundary label match for city '{name}'")
            fids.extend(matches["bounds_fid"].tolist())
        return fids

    # ══════════════════════════════════════════════════════════════════
    # Global counts
    # ══════════════════════════════════════════════════════════════════
    hq_fids = load_hq_fids(threshold=0.10)
    n_ml_restricted = len(hq_fids)

    mw.section("Global counts")
    mw.add("nCities", n_cities)
    mw.add("nCountries", n_countries)
    mw.add("nTotalM", n_total / 1e6, ".1f")
    mw.add("nClassifiedM", n_classified / 1e6, ".1f")
    mw.add("pctClassified", pct_classified, ".1f")
    mw.add("pctExcluded", pct_excluded, ".1f")
    mw.add("nMLRestrictedCities", n_ml_restricted)

    # ══════════════════════════════════════════════════════════════════
    # Plate 1: Octant counts and shares
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 1 — Octant counts and shares")
    oct_counts = classified["octant"].value_counts()
    total_oct = oct_counts.sum()

    for o in OCTANT_ORDER:
        n = oct_counts.get(o, 0)
        pct = 100 * n / total_oct
        mw.add(f"oct{o}countM", n / 1e6, ".1f")
        mw.add(f"oct{o}pct", pct, ".1f")

    # Intense types combined
    intense_pct = sum(oct_counts.get(o, 0) for o in ["HHH", "HHL", "HLH", "HLL"]) / total_oct * 100
    mw.add("octIntensePct", intense_pct, ".1f")
    light_pct = sum(oct_counts.get(o, 0) for o in ["LHH", "LHL", "LLH", "LLL"]) / total_oct * 100
    mw.add("pctLightTypes", light_pct, ".0f")
    intense_attached_pct = sum(oct_counts.get(o, 0) for o in ["HHH", "HHL"]) / total_oct * 100
    mw.add("pctIntenseAttached", intense_attached_pct, ".0f")

    # ══════════════════════════════════════════════════════════════════
    # Plate 1: Octant median axis values (Table 1)
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 1 — Octant median metric values (Table 1)")
    fsi_col = AXIS_COLS["intensity"]
    cont_col = AXIS_COLS["continuity"]  # frontage_max
    mad_col = AXIS_COLS["irregularity"]
    retail_col = SVC_COLS["retail"]

    for o in OCTANT_ORDER:
        mask = classified["octant"] == o
        sub = classified[mask]
        mw.add(f"oct{o}fsi", sub[fsi_col].median(), ".2f")
        mw.add(f"oct{o}cont", sub[cont_col].median(), ".3f")
        mw.add(f"oct{o}mad", sub[mad_col].median(), ".2f")
        mw.add(f"oct{o}retail", sub[retail_col].median(), ".0f")

    # ══════════════════════════════════════════════════════════════════
    # Plate 1: Axis independence statistics
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 1 — Axis correlations and independence")
    axes_data = classified[[fsi_col, cont_col, mad_col]].dropna()
    n_axes = len(axes_data)
    mw.add("nAxesM", n_axes / 1e6, ".1f")

    # Pearson correlations
    corr_ic = np.corrcoef(axes_data[fsi_col], axes_data[cont_col])[0, 1]
    corr_ii = np.corrcoef(axes_data[fsi_col], axes_data[mad_col])[0, 1]
    corr_ci = np.corrcoef(axes_data[cont_col], axes_data[mad_col])[0, 1]
    mw.add("rIntCont", corr_ic, ".2f")
    mw.add("rIntIrreg", corr_ii, ".2f")
    mw.add("rContIrreg", corr_ci, ".2f")

    # City-level Continuity vs Intensity correlation (frontage vs FSI, city medians)
    _city_med = classified.groupby("bounds_fid")[[cont_col, fsi_col]].median().dropna()
    mw.add("rFrontageFSIcity", pearsonr(_city_med[cont_col], _city_med[fsi_col])[0], ".2f")

    # VIF
    from sklearn.preprocessing import StandardScaler

    X_ax = StandardScaler().fit_transform(axes_data.values)
    R = np.corrcoef(X_ax, rowvar=False)
    R_inv = np.linalg.inv(R)
    max_vif = max(R_inv[i, i] for i in range(3))
    mw.add("maxVIF", max_vif, ".1f")

    # Observed/expected balance
    p_i = (axes_data[fsi_col] >= 1.0).mean()
    p_c = (axes_data[cont_col] >= 0.75).mean()
    p_r = (axes_data[mad_col] >= 4.0).mean()
    ratios = []
    for o in OCTANT_ORDER:
        obs = oct_counts.get(o, 0)
        p = 1.0
        p *= p_i if o[0] == "H" else (1 - p_i)
        p *= p_c if o[1] == "H" else (1 - p_c)
        p *= p_r if o[2] == "H" else (1 - p_r)
        exp = p * n_axes
        if exp > 0:
            ratios.append(obs / exp)
    mw.add("obsExpMin", min(ratios), ".2f")
    mw.add("obsExpMax", max(ratios), ".2f")

    # Cramer's V
    obs_arr = np.array([oct_counts.get(o, 0) for o in OCTANT_ORDER], dtype=float)
    exp_arr = np.array(
        [
            n_axes
            * (p_i if o[0] == "H" else 1 - p_i)
            * (p_c if o[1] == "H" else 1 - p_c)
            * (p_r if o[2] == "H" else 1 - p_r)
            for o in OCTANT_ORDER
        ]
    )
    chi2 = np.sum((obs_arr - exp_arr) ** 2 / exp_arr)
    cramers_v = np.sqrt(chi2 / (n_axes * 1))  # min(2,2,2)-1 = 1
    mw.add("cramersV", cramers_v, ".2f")

    # ══════════════════════════════════════════════════════════════════
    # Plate 1: Discrimination (eta-squared on non-axis variables)
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 1 — Discrimination (eta-squared)")
    morph_available = [c for c in MORPH_COLS_LIST if c in classified.columns]

    eta2_map = {}
    for col in morph_available:
        valid = classified[[col, "octant"]].dropna(subset=[col])
        vals = valid[col].values
        grand_mean = vals.mean()
        ss_total = np.sum((vals - grand_mean) ** 2)
        ss_between = 0.0
        for o in OCTANT_ORDER:
            g = valid.loc[valid["octant"] == o, col].values
            if len(g) > 0:
                ss_between += len(g) * (np.mean(g) - grand_mean) ** 2
        eta2_map[col] = ss_between / ss_total if ss_total > 0 else 0

    # Key eta-squared values cited in text
    eta2_vars = {
        "gsi": "cc_block_covered_ratio_median_400_wt",
        "height": "cc_mean_height_median_400_wt",
        "meanFloors": "cc_block_l_median_400_wt",
        "bldgDensity": "cc_building_400_nw",
    }
    for name, col in eta2_vars.items():
        if col in eta2_map:
            mw.add(f"etaSq{name[0].upper()}{name[1:]}", eta2_map[col], ".2f")

    # Intensity candidate discrimination (FSI vs height vs height_var vs GSI)
    intensity_candidates = {
        "fsi": "cc_block_far_median_400_wt",
        "height": "cc_mean_height_median_400_wt",
        "heightVar": "cc_mean_height_mad_400_wt",
        "gsiCand": "cc_block_covered_ratio_median_400_wt",
    }
    for name, col in intensity_candidates.items():
        if col in eta2_map:
            mw.add(f"etaSqCand{name[0].upper()}{name[1:]}", eta2_map[col], ".2f")

    # Mutual correlation among intensity candidates
    cand_cols = [
        "cc_block_far_median_400_wt",
        "cc_mean_height_median_400_wt",
        "cc_mean_height_mad_400_wt",
        "cc_block_covered_ratio_median_400_wt",
    ]
    cand_available = [c for c in cand_cols if c in classified.columns]
    if len(cand_available) >= 2:
        cand_corr = classified[cand_available].corr().values
        max_r_intensity = 0
        for i in range(len(cand_available)):
            for j in range(i + 1, len(cand_available)):
                max_r_intensity = max(max_r_intensity, abs(cand_corr[i, j]))
        mw.add("maxRIntensityCandidates", max_r_intensity, ".2f")

    # PCA top 3 (on complete cases only)
    from sklearn.decomposition import PCA

    morph_complete = classified[morph_available].dropna()
    X = StandardScaler().fit_transform(morph_complete.values)
    pca = PCA()
    pca.fit(X)
    pca3 = sum(pca.explained_variance_ratio_[:3]) * 100
    mw.add("pcaTopThree", pca3, ".0f")

    n_morph_vars = len(morph_available)
    mw.add("nMorphVars", n_morph_vars)

    # ══════════════════════════════════════════════════════════════════
    # Plate 1: Missing data rates
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 1 — Missing data rates")
    # Missing = NaN or zero (streets with no buildings in range have NaN/0)
    fsi_400_col = AXIS_COLS["intensity"]
    fsi_400_missing = (df[fsi_400_col].isna() | (df[fsi_400_col] == 0)).mean() * 100
    mw.add("pctMissingFSIfourHundred", fsi_400_missing, ".0f")
    # Pure NaN rate
    fsi_400_nan = df[fsi_400_col].isna().mean() * 100
    mw.add("pctNaNFSIfourHundred", fsi_400_nan, ".0f")

    # Also check 200m alternative if available
    fsi_200_col = "cc_block_far_median_200_wt"
    if fsi_200_col in df.columns:
        fsi_200_missing = (df[fsi_200_col].isna() | (df[fsi_200_col] == 0)).mean() * 100
        mw.add("pctMissingFSItwoHundred", fsi_200_missing, ".0f")
        fsi_200_nan = df[fsi_200_col].isna().mean() * 100
        mw.add("pctNaNFSItwoHundred", fsi_200_nan, ".0f")

    # ══════════════════════════════════════════════════════════════════
    # Plate 2/3: City-level axis values
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 2/3 — City-level axis values")
    city_meta = classified.merge(bounds[["bounds_fid", "label", "country"]], on="bounds_fid")
    city_axes = city_meta.groupby("bounds_fid").agg(
        {
            fsi_col: "median",
            cont_col: "median",
            mad_col: "median",
            "country": "first",
            "label": "first",
        }
    )

    def city_val(label, col, fmt=".2f"):
        row = city_axes[city_axes["label"] == label]
        if len(row) == 0:
            return np.nan
        return row[col].iloc[0]

    # Mediterranean FSI
    for city in ["Barcelona", "Athens", "Madrid"]:
        v = city_val(city, fsi_col)
        name = city.replace(" ", "")
        mw.add(f"fsi{name}", v, ".2f")

    # Nordic axis values
    nordic_cities = ["Oslo", "Bergen", "Helsinki", "Stockholm"]
    for city in nordic_cities:
        v_fsi = city_val(city, fsi_col)
        v_mad = city_val(city, mad_col)
        name = city.replace(" ", "")
        mw.add(f"fsi{name}", v_fsi, ".2f")
        mw.add(f"mad{name}", v_mad, ".1f")

    # Belgian city MAD values (organic medieval growth examples)
    belgian_mad_cities = ["Liège", "Brussels"]
    for city in belgian_mad_cities:
        v_mad = city_val(city, mad_col)
        # Strip diacritics for macro name
        name = city.replace(" ", "").replace("è", "e").replace("é", "e")
        mw.add(f"mad{name}", v_mad, ".1f")

    # NL/BE continuity and MAD
    nl_cities = city_axes[city_axes["country"] == "Netherlands"]
    be_cities = city_axes[city_axes["country"] == "Belgium"]
    mw.add("contNLmed", nl_cities[cont_col].median(), ".2f")
    mw.add("contBEmed", be_cities[cont_col].median(), ".2f")
    mw.add("madNLmin", nl_cities[mad_col].min(), ".1f")
    mw.add("madNLmax", nl_cities[mad_col].max(), ".1f")
    mw.add("madNLmed", nl_cities[mad_col].median(), ".1f")
    mw.add("madBEmin", be_cities[mad_col].min(), ".1f")
    mw.add("madBEmax", be_cities[mad_col].max(), ".1f")
    mw.add("madBEmed", be_cities[mad_col].median(), ".1f")

    # Country-level median FSI, continuity, MAD for Plate 2/3 text
    for country_name, code in [
        ("Spain", "ES"),
        ("Bulgaria", "BG"),
        ("Slovakia", "SK"),
        ("Portugal", "PT"),
        ("Austria", "AT"),
        ("Italy", "IT"),
        ("Greece", "EL"),
        ("Latvia", "LV"),
        ("Estonia", "EE"),
        ("France", "FR"),
        ("Ireland", "IE"),
        ("Germany", "DE"),
        ("Norway", "NO"),
        ("Switzerland", "CH"),
        ("Croatia", "HR"),
    ]:
        cc = city_axes[city_axes["country"] == country_name]
        if len(cc) == 0:
            continue
        mw.add(f"fsiCtry{code}", cc[fsi_col].median(), ".2f")
        mw.add(f"contCtry{code}", cc[cont_col].median(), ".2f")
        mw.add(f"madCtry{code}", cc[mad_col].median(), ".1f")

    # Within-city continuity percentages (pct streets >= frontage threshold)
    for city_name, macro_name in [
        ("Barcelona", "pctContBarcelona"),
        ("Athens", "pctContAthens"),
        ("Madrid", "pctContMadrid"),
        ("Amsterdam", "pctContAmsterdam"),
        ("Brussels", "pctContBrussels"),
    ]:
        mask = classified["bounds_fid"].isin(city_fids([city_name]))
        if mask.sum() == 0:
            continue
        pct = 100 * (classified.loc[mask, cont_col] >= 0.75).sum() / mask.sum()
        mw.add(macro_name, pct, ".0f")

    # NL continuity CV
    nl_cont_cv = nl_cities[cont_col].std() / nl_cities[cont_col].mean()
    mw.add("cvNLcont", nl_cont_cv, ".2f")

    # Poland: city-level median orientation MAD (cited at atlas.tex:94)
    pl_cities = city_axes[city_axes["country"] == "Poland"]
    if len(pl_cities) > 0:
        mw.add("madPolandAvg", pl_cities[mad_col].median(), ".1f")

    # Country-cluster service-distance medians (replace manual prose thresholds).
    # Clusters used in the Plate 9 continental-gradient discussion.
    CLUSTER_TREES_COOL = [
        "Norway",
        "Sweden",
        "Finland",
        "Denmark",
        "Estonia",
        "Latvia",
        "Lithuania",
        "Poland",
        "Germany",
    ]
    CLUSTER_TREES_WARM = ["Italy", "Spain", "Greece", "Portugal"]
    CLUSTER_EAT_SOUTH = ["Italy", "Spain", "Greece", "Portugal"]
    CLUSTER_EAT_NORTH = ["Norway", "Sweden", "Finland", "Denmark"]

    def _cluster_city_median(cluster, col):
        """Median across cities (city = bounds_fid) of city-level medians for col,
        restricted to the given country cluster."""
        meta = classified.merge(bounds[["bounds_fid", "country"]], on="bounds_fid")
        meta = meta[meta["country"].isin(cluster)]
        if len(meta) == 0:
            return float("nan")
        city_med = meta.groupby("bounds_fid")[col].median()
        return float(city_med.median())

    _trees_col = SVC_COLS["trees"]
    _eatdrink_col = SVC_COLS["eat_drink"]
    mw.add("distTreesCoolMed", _cluster_city_median(CLUSTER_TREES_COOL, _trees_col), ".0f")
    mw.add("distTreesWarmMed", _cluster_city_median(CLUSTER_TREES_WARM, _trees_col), ".0f")
    mw.add("distEatDrinkSouthMed", _cluster_city_median(CLUSTER_EAT_SOUTH, _eatdrink_col), ".0f")
    mw.add("distEatDrinkNorthMed", _cluster_city_median(CLUSTER_EAT_NORTH, _eatdrink_col), ".0f")

    # ══════════════════════════════════════════════════════════════════
    # Plate 4: Building morphometrics by octant
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 4 — Building morphometrics by octant")
    height_col = MORPH_COLS["height"]
    # Per-octant morphometric macros
    morph_macro_map = {
        "height": ("height", ".1f"),
        "area": ("area", ".0f"),
        "perimeter": ("perim", ".0f"),
        "corners": ("corners", ".0f"),
        "compactness": ("compact", ".2f"),
        "volume": ("volume", ".0f"),
        "gsi": ("gsi", ".2f"),
        "osr": ("osr", ".2f"),
        "mean_floors": ("floors", ".1f"),
        "block_perim": ("blkPerim", ".0f"),
        "bldg_count": ("bldgCount", ".0f"),
        "block_count": ("blkCount", ".0f"),
    }
    for o in OCTANT_ORDER:
        mask = classified["octant"] == o
        sub = classified[mask]
        # FSI and continuity (full precision)
        if fsi_col in sub.columns:
            mw.add(f"oct{o}fsiFull", sub[fsi_col].median(), ".2f")
        if cont_col in sub.columns:
            mw.add(f"oct{o}contFull", sub[cont_col].median(), ".2f")
        # All morphometric columns
        for key, (suffix, fmt) in morph_macro_map.items():
            col = MORPH_COLS.get(key)
            if col and col in sub.columns:
                mw.add(f"oct{o}{suffix}", sub[col].median(), fmt)

    # Business service span (max - min across octants)
    business_col = SVC_COLS.get("business")
    if business_col and business_col in classified.columns:
        oct_business = classified.groupby("octant")[business_col].median()
        mw.add("businessSpan", oct_business.max() - oct_business.min(), ".0f")

    # Network reach per octant: median count of streets reachable within
    # the morphological kernel distance (kernelDist = 400m).
    reach_col = "cc_density_400"
    if reach_col in classified.columns:
        for o in OCTANT_ORDER:
            mask = classified["octant"] == o
            mw.add(f"oct{o}reach", classified.loc[mask, reach_col].median(), ".0f")

    # ══════════════════════════════════════════════════════════════════
    # Plate 5: Service distances — continental order and by octant
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 5 — Service distances")
    city_svc = classified.groupby("bounds_fid")[list(SVC_COLS.values())].median()

    for name, col in SVC_COLS.items():
        if col not in classified.columns:
            continue
        # Continental median (median across all classified streets)
        med = classified[col].median()
        macro_name = "svc" + "".join(w.capitalize() for w in name.split("_")) + "Med"
        mw.add(macro_name, med, ".0f")

        # By octant
        oct_med = classified.groupby("octant")[col].median()
        for o in OCTANT_ORDER:
            v = oct_med.get(o, np.nan)
            mw.add(f"svc{name.replace('_', '').title()}{o}", v, ".0f")

    # Retail fold difference HHH→LLL
    retail_hhh = classified.loc[classified["octant"] == "HHH", retail_col].median()
    retail_lll = classified.loc[classified["octant"] == "LLL", retail_col].median()
    mw.add("retailFoldHHHtoLLL", retail_lll / retail_hhh, ".1f")

    # Eat & drink fold difference
    ed_col = SVC_COLS["eat_drink"]
    ed_hhh = classified.loc[classified["octant"] == "HHH", ed_col].median()
    ed_lll = classified.loc[classified["octant"] == "LLL", ed_col].median()
    mw.add("eatDrinkFoldHHHtoLLL", ed_lll / ed_hhh, ".1f")

    # Transport fold difference
    tr_col = SVC_COLS["transport"]
    tr_hhh = classified.loc[classified["octant"] == "HHH", tr_col].median()
    tr_lll = classified.loc[classified["octant"] == "LLL", tr_col].median()
    mw.add("transportFoldHHHtoLLL", tr_lll / tr_hhh, ".1f")

    # City-level restaurant distances
    ed_city = city_meta.groupby("bounds_fid").agg({ed_col: "median", "label": "first"})
    for city in ["Oslo", "Bergen", "Barcelona", "Athens"]:
        row = ed_city[ed_city["label"] == city]
        if len(row) > 0:
            name = city.replace(" ", "")
            mw.add(f"eatDrink{name}", row[ed_col].iloc[0], ".0f")

    # ══════════════════════════════════════════════════════════════════
    # Plate 8: Demographics by octant
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 8 — Demographics by octant")
    dens_col = DEMO_COLS["density"]
    youth_col = DEMO_COLS["youth"]
    elderly_col = DEMO_COLS["elderly"]

    # Helper: demographic percentage columns are 0–1 fractions; multiply by 100
    def _pct(val):
        return val * 100

    for o in OCTANT_ORDER:
        mask = classified["octant"] == o
        sub = classified[mask]
        if dens_col in sub.columns:
            mw.add(f"oct{o}popDens", sub[dens_col].median(), ".0f")
        if youth_col in sub.columns:
            mw.add(f"oct{o}youth", _pct(sub[youth_col].median()), ".0f")
        if elderly_col in sub.columns:
            mw.add(f"oct{o}elderly", _pct(sub[elderly_col].median()), ".0f")

    # Per-octant employment and working-age
    emp_col = DEMO_COLS["employment"]
    wa_col = DEMO_COLS["working_age"]
    for o in OCTANT_ORDER:
        mask = classified["octant"] == o
        sub = classified[mask]
        if emp_col in sub.columns:
            mw.add(f"oct{o}employ", _pct(sub[emp_col].median()), ".0f")
        if wa_col in sub.columns:
            mw.add(f"oct{o}workAge", _pct(sub[wa_col].median()), ".0f")

    # Intense vs Light ranges
    intense_types = ["HHH", "HHL", "HLH", "HLL"]
    light_types = ["LHH", "LHL", "LLH", "LLL"]
    if youth_col in classified.columns:
        intense_youth = _pct(classified[classified["octant"].isin(intense_types)][youth_col].median())
        light_youth = _pct(classified[classified["octant"].isin(light_types)][youth_col].median())
        mw.add("youthIntense", intense_youth, ".0f")
        mw.add("youthLight", light_youth, ".0f")
    if elderly_col in classified.columns:
        elderly_by_oct = classified.groupby("octant")[elderly_col].median() * 100
        mw.add("elderlyMin", elderly_by_oct.min(), ".0f")
        mw.add("elderlyMax", elderly_by_oct.max(), ".0f")
    if wa_col in classified.columns:
        wa_by_oct = classified.groupby("octant")[wa_col].median() * 100
        intense_wa = [wa_by_oct.get(o, 0) for o in intense_types]
        light_wa = [wa_by_oct.get(o, 0) for o in light_types]
        mw.add("workAgeIntenseMin", min(intense_wa), ".0f")
        mw.add("workAgeIntenseMax", max(intense_wa), ".0f")
        mw.add("workAgeLightMin", min(light_wa), ".0f")
        mw.add("workAgeLightMax", max(light_wa), ".0f")
    if emp_col in classified.columns:
        emp_by_oct = classified.groupby("octant")[emp_col].median() * 100
        intense_emp = [emp_by_oct.get(o, 0) for o in intense_types]
        light_emp = [emp_by_oct.get(o, 0) for o in light_types]
        mw.add("employIntenseMin", min(intense_emp), ".0f")
        mw.add("employIntenseMax", max(intense_emp), ".0f")
        mw.add("employLightMin", min(light_emp), ".0f")
        mw.add("employLightMax", max(light_emp), ".0f")

    # Intense/Light pop density bounds
    if dens_col in classified.columns:
        intense_dens = [classified.loc[classified["octant"] == o, dens_col].median() for o in intense_types]
        light_dens = [classified.loc[classified["octant"] == o, dens_col].median() for o in light_types]
        mw.add("popDensIntenseMin", min(intense_dens), ".0f")
        mw.add("popDensLightMax", max(light_dens), ".0f")

    # Within-city robustness of demographic gradients (appendix Table tab:demo-robust).
    # For each demographic: pooled Light-Intense gap (pp), a city-demeaned effect size
    # (Cliff's delta, which removes between-city composition), and the share of cities
    # whose within-city direction matches the pooled sign. Distinguishes genuine
    # morphological gradients (child, working-age) from between-city artefacts (employment).
    mw.section("Appendix — within-city demographic robustness")
    from scipy.stats import rankdata

    _drng = np.random.default_rng(42)

    def _cliffs_delta(a, b, s=20000):
        """Cliff's delta for (b vs a): 2*P(b>a)-1, on a fixed-seed subsample."""
        a = a[np.isfinite(a)]
        b = b[np.isfinite(b)]
        if len(a) == 0 or len(b) == 0:
            return float("nan")
        if len(a) > s:
            a = _drng.choice(a, s, replace=False)
        if len(b) > s:
            b = _drng.choice(b, s, replace=False)
        na, nb = len(a), len(b)
        r = rankdata(np.concatenate([a, b]))
        u = r[na:].sum() - nb * (nb + 1) / 2.0
        return 2.0 * (u / (na * nb)) - 1.0

    for _name, _col in [("Child", youth_col), ("Work", wa_col), ("Elder", elderly_col), ("Emp", emp_col)]:
        if _col not in classified.columns:
            continue
        _d = classified[["octant", "bounds_fid", _col]].dropna(subset=[_col]).copy()
        _d["_g"] = np.where(_d["octant"].isin(intense_types), "I", np.where(_d["octant"].isin(light_types), "L", ""))
        _d = _d[_d["_g"] != ""]
        _iv = _d.loc[_d["_g"] == "I", _col].to_numpy()
        _lv = _d.loc[_d["_g"] == "L", _col].to_numpy()
        _gap = (np.median(_lv) - np.median(_iv)) * 100.0
        mw.add(f"demo{_name}Gap", _gap, "+.1f")
        _d["_dm"] = _d[_col] - _d.groupby("bounds_fid")[_col].transform("median")
        _delta = _cliffs_delta(_d.loc[_d["_g"] == "I", "_dm"].to_numpy(), _d.loc[_d["_g"] == "L", "_dm"].to_numpy())
        mw.add(f"demo{_name}Delta", _delta, "+.2f")
        _sign_pos = _gap >= 0
        _cons = _tot = 0
        for _fid, _sub in _d.groupby("bounds_fid"):
            _si = _sub.loc[_sub["_g"] == "I", _col]
            _sl = _sub.loc[_sub["_g"] == "L", _col]
            if len(_si) >= 30 and len(_sl) >= 30:
                _diff = _sl.median() - _si.median()
                if np.isfinite(_diff):
                    _tot += 1
                    if (_diff >= 0) == _sign_pos:
                        _cons += 1
        mw.add(f"demo{_name}Pct", (_cons / _tot * 100.0) if _tot else float("nan"), ".0f")

    # ══════════════════════════════════════════════════════════════════
    # Plate 9: Green vs retail correlation
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 9 — Green vs retail correlation")
    from scipy.stats import spearmanr

    green_col = SVC_COLS["green"]
    trees_col = SVC_COLS["trees"]
    city_green_retail = city_svc[[retail_col, green_col]].dropna()
    r_gr, p_gr = pearsonr(city_green_retail[retail_col], city_green_retail[green_col])
    rho_gr, p_rho_gr = spearmanr(city_green_retail[retail_col], city_green_retail[green_col])
    n_gr = len(city_green_retail)
    mw.add("rGreenRetail", r_gr, ".2f")
    mw.add("pGreenRetail", p_gr, ".2f")
    mw.add("rhoGreenRetail", rho_gr, ".2f")
    mw.add("pRhoGreenRetail", p_rho_gr, ".2f")
    mw.add("nGreenRetail", n_gr)

    # Leverage diagnostic: leave-one-out delta-r. Report the city whose removal
    # produces the largest absolute change in Pearson r.
    xs = city_green_retail[retail_col].to_numpy(dtype=float)
    ys = city_green_retail[green_col].to_numpy(dtype=float)
    fids = city_green_retail.index.to_numpy()
    full_r, _ = pearsonr(xs, ys)
    deltas = []
    for i in range(len(xs)):
        mask = np.arange(len(xs)) != i
        if mask.sum() >= 3:
            ri, _ = pearsonr(xs[mask], ys[mask])
            deltas.append((fids[i], abs(ri - full_r), ri))
    if deltas:
        worst_fid, worst_delta, worst_r = max(deltas, key=lambda t: t[1])
        worst_label = label_map.get(int(worst_fid), str(worst_fid))
        mw.add("leverageGreenRetailCity", worst_label)
        mw.add("leverageGreenRetailDelta", worst_delta, ".3f")
        mw.add("leverageGreenRetailRwithout", worst_r, ".2f")

    # ══════════════════════════════════════════════════════════════════
    # Plate 10: Paired comparisons
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 10 — Paired comparisons")
    all_metric_cols = list(
        dict.fromkeys(
            list(SVC_COLS.values())
            + list(MORPH_COLS.values())
            + list(DEMO_COLS.values())
            + list(AXIS_COLS.values())
            + list(CENTRALITY_COLS.values())
        )
    )
    available_cols = [c for c in all_metric_cols if c in classified.columns]
    city_df = classified.groupby("bounds_fid")[available_cols].median()
    city_country = city_meta.groupby("bounds_fid")[["country", "label"]].first()
    city_df = city_df.join(city_country)

    def group_by_filter(filt):
        if "country" in filt:
            return city_df[city_df["country"].isin(filt["country"])]
        else:
            return city_df[city_df.index.isin(city_fids(filt["cities"]))]

    def med(group, col):
        if col not in group.columns:
            return np.nan
        return float(pd.to_numeric(group[col], errors="coerce").median())

    def city_range(group, col, fmt=".0f"):
        vals = pd.to_numeric(group[col], errors="coerce").dropna()
        return float(vals.min()), float(vals.max())

    # ── Plate 10: 4 paired comparisons, 10 standard variables each ────
    # Variables: FSI, Height, GSI, Frontage ratio, MAD, StreetDens,
    #            Retail, Eat & drink, Trees, Green
    dens800 = CENTRALITY_COLS["density_800"]
    gsi_col = MORPH_COLS["gsi"]

    def emit_pair(prefix_a, prefix_b, group_a, group_b):
        mw.add(f"comp{prefix_a}FSI", med(group_a, fsi_col), ".2f")
        mw.add(f"comp{prefix_b}FSI", med(group_b, fsi_col), ".2f")
        mw.add(f"comp{prefix_a}Height", med(group_a, height_col), ".1f")
        mw.add(f"comp{prefix_b}Height", med(group_b, height_col), ".1f")
        mw.add(f"comp{prefix_a}GSI", med(group_a, gsi_col), ".2f")
        mw.add(f"comp{prefix_b}GSI", med(group_b, gsi_col), ".2f")
        mw.add(f"comp{prefix_a}Cont", med(group_a, cont_col), ".2f")
        mw.add(f"comp{prefix_b}Cont", med(group_b, cont_col), ".2f")
        mw.add(f"comp{prefix_a}MAD", med(group_a, mad_col), ".1f")
        mw.add(f"comp{prefix_b}MAD", med(group_b, mad_col), ".1f")
        if dens800 in city_df.columns:
            mw.add(f"comp{prefix_a}StreetDens", med(group_a, dens800), ".0f")
            mw.add(f"comp{prefix_b}StreetDens", med(group_b, dens800), ".0f")
        mw.add(f"comp{prefix_a}Retail", med(group_a, retail_col), ".0f")
        mw.add(f"comp{prefix_b}Retail", med(group_b, retail_col), ".0f")
        mw.add(f"comp{prefix_a}EatDrink", med(group_a, ed_col), ".0f")
        mw.add(f"comp{prefix_b}EatDrink", med(group_b, ed_col), ".0f")
        mw.add(f"comp{prefix_a}Trees", med(group_a, trees_col), ".0f")
        mw.add(f"comp{prefix_b}Trees", med(group_b, trees_col), ".0f")
        mw.add(f"comp{prefix_a}Green", med(group_a, green_col), ".0f")
        mw.add(f"comp{prefix_b}Green", med(group_b, green_col), ".0f")

    # 1. Nordic vs Mediterranean (5 vs 5 cities)
    nordic_g = group_by_filter({"cities": ["Oslo", "Bergen", "Helsinki", "Stockholm", "Copenhagen"]})
    med_g = group_by_filter({"cities": ["Barcelona", "Athens", "Madrid", "Naples", "Thessaloniki"]})
    emit_pair("Nordic", "Med", nordic_g, med_g)

    # 2. Netherlands vs Belgium (3 vs 3 cities — network contrast at shared continuity)
    nl_g = group_by_filter({"cities": ["Amsterdam", "Utrecht", "Rotterdam"]})
    be_g = group_by_filter({"cities": ["Brussels", "Ghent", "Antwerp"]})
    emit_pair("NL", "BE", nl_g, be_g)

    # 3. Low Countries (NL + BE) vs Baltic (EE + LV + LT)
    lc_g = group_by_filter({"country": ["Netherlands", "Belgium"]})
    baltic_g = group_by_filter({"country": ["Estonia", "Latvia", "Lithuania"]})
    emit_pair("LC", "Baltic", lc_g, baltic_g)

    # 4. Poland vs Romania
    pl_g = group_by_filter({"country": ["Poland"]})
    ro_g = group_by_filter({"country": ["Romania"]})
    emit_pair("PL", "RO", pl_g, ro_g)

    # ══════════════════════════════════════════════════════════════════
    # Plate 11: Density quintile form gaps
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 11 — Density quintile form gaps")
    valid_dens = classified[classified[dens_col] > 0].copy()
    valid_dens["dq"] = pd.qcut(valid_dens[dens_col], 5, labels=False, duplicates="drop") + 1
    dq_stats = valid_dens.groupby("dq")[dens_col].median()

    q_words = {1: "One", 2: "Two", 3: "Three", 4: "Four", 5: "Five"}
    for q in range(1, 6):
        if q in dq_stats.index:
            mw.add(f"dqMedian{q_words[q]}", dq_stats[q], ".0f")

    # Form gaps by quintile for retail and education
    for svc_name, svc_col in [
        ("retail", retail_col),
        ("education", SVC_COLS["education"]),
        ("transport", SVC_COLS["transport"]),
        ("green", SVC_COLS["green"]),
    ]:
        if svc_col not in valid_dens.columns:
            continue
        qo = valid_dens.groupby(["dq", "octant"])[svc_col].median().unstack("octant")
        for q in range(1, 6):
            if q not in qo.index:
                continue
            row = qo.loc[q]
            lo, hi = row.min(), row.max()
            gap = hi - lo
            best = row.idxmin()
            worst = row.idxmax()
            sn = svc_name.capitalize()
            qw = q_words[q]
            mw.add(f"dq{sn}Q{qw}lo", lo, ".0f")
            mw.add(f"dq{sn}Q{qw}hi", hi, ".0f")
            mw.add(f"dq{sn}Q{qw}gap", gap, ".0f")
            mw.add(f"dq{sn}Q{qw}best", best)
            mw.add(f"dq{sn}Q{qw}worst", worst)

    # Continental retail median (street-level, consistent with svcRetailMed)
    continental_retail_med = classified[retail_col].median()
    mw.add("retailContMed", continental_retail_med, ".0f")
    # Form gap as % of continental median at Q3
    if 3 in qo.index:
        row_q3 = valid_dens.groupby(["dq", "octant"])[retail_col].median().unstack("octant").loc[3]
        gap_q3 = row_q3.max() - row_q3.min()
        mw.add("dqRetailQThreegapPct", 100 * gap_q3 / continental_retail_med, ".0f")

    # ══════════════════════════════════════════════════════════════════
    # Plate 6: Desert fractions
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 6 — Desert fractions (no service within 400m)")
    DESERT_THRESHOLD = 400
    for name, col in SVC_COLS.items():
        if col not in classified.columns:
            continue
        vals = classified[["octant", col]].dropna(subset=[col])
        vals = vals.copy()
        vals["is_desert"] = (vals[col] >= DESERT_THRESHOLD).astype(float)
        by_oct = vals.groupby("octant")["is_desert"].mean() * 100
        for o in OCTANT_ORDER:
            v = by_oct.get(o, np.nan)
            sn = "".join(w.capitalize() for w in name.split("_"))
            mw.add(f"desert{sn}{o}", v, ".0f")

    # ══════════════════════════════════════════════════════════════════
    # Plate 7: P25-P75 inequality gaps
    # ══════════════════════════════════════════════════════════════════
    mw.section("Plate 7 — P25/P75 unevenness")
    for name, col in SVC_COLS.items():
        if col not in classified.columns:
            continue
        for o in OCTANT_ORDER:
            ov = classified.loc[classified["octant"] == o, col].dropna()
            if len(ov) < 50:
                continue
            p25 = ov.quantile(0.25)
            p75 = ov.quantile(0.75)
            iqr = p75 - p25
            sn = "".join(w.capitalize() for w in name.split("_"))
            mw.add(f"iqr{sn}{o}", iqr, ".0f")
            mw.add(f"ptwofive{sn}{o}", p25, ".0f")
            mw.add(f"psevenfive{sn}{o}", p75, ".0f")

    # IQR ranges across types for specific categories
    for name, col in [
        ("trees", SVC_COLS["trees"]),
        ("transport", SVC_COLS["transport"]),
        ("accommodation", SVC_COLS["accommodation"]),
        ("arts", SVC_COLS["arts"]),
    ]:
        if col not in classified.columns:
            continue
        iqrs = []
        for o in OCTANT_ORDER:
            ov = classified.loc[classified["octant"] == o, col].dropna()
            if len(ov) >= 50:
                iqrs.append(ov.quantile(0.75) - ov.quantile(0.25))
        if iqrs:
            sn = name.capitalize()
            mw.add(f"iqr{sn}Min", min(iqrs), ".0f")
            mw.add(f"iqr{sn}Max", max(iqrs), ".0f")

    # ══════════════════════════════════════════════════════════════════
    # POI validation thresholds (from companion data paper outputs)
    # ══════════════════════════════════════════════════════════════════
    mw.section("POI validation thresholds (derived from data paper outputs)")
    import os as _os

    _data_root = Path(_os.environ.get("T2E_DATA_DIR", ""))
    f1_csv = _data_root / "paper_data_outputs" / "csv" / "pointa_accessibility_nearest_tolerance_agreement.csv"
    if f1_csv.exists():
        f1_df = pd.read_csv(f1_csv)
        n_validation = f1_df["bounds_fid"].nunique()
        mw.add("nValidationCities", n_validation)

        # Find the smallest tolerance at which median F1 (across cities)
        # reaches 0.80 for each category.
        def _min_tol_for_f1(category, threshold=0.80):
            sub = f1_df[f1_df["category"] == category]
            if sub.empty:
                return None
            med = sub.groupby("tolerance_m")["f1"].median().sort_index()
            ok = med[med >= threshold]
            return int(ok.index.min()) if len(ok) else None

        good_cats = ("retail", "eat_and_drink", "business_and_services")
        other_cats = ("education", "health_and_medical")
        good_tols = [_min_tol_for_f1(c) for c in good_cats]
        other_tols = [_min_tol_for_f1(c) for c in other_cats]
        accom_tol = _min_tol_for_f1("accommodation")

        if all(t is not None for t in good_tols):
            mw.add("poiNearDistGood", float(max(good_tols)), ".0f")
        if all(t is not None for t in other_tols):
            mw.add("poiNearDistOther", float(max(other_tols)), ".0f")
        if accom_tol is not None:
            mw.add("poiNearDistAccom", float(accom_tol), ".0f")

    # ══════════════════════════════════════════════════════════════════
    # Threshold sensitivity: how do octant shares respond to ±20%
    # variation in each axis threshold? Emits sensitivity.tex (LaTeX
    # table) plus per-octant share macros.
    # ══════════════════════════════════════════════════════════════════
    mw.section("Threshold sensitivity (±20%) — octant shares")
    # Baselines match classify_octants in atlas_common.py: FSI >= 1.0,
    # frontage_max >= 0.75, orientation MAD >= 4.0.
    BASE_T_FSI, BASE_T_CONT, BASE_T_MAD = 1.0, 0.75, 4.0

    def _classify_at(t_fsi, t_cont, t_mad):
        """Classify the axis-complete subset at the given thresholds.
        Returns a Series mapping octant code -> share (0..1)."""
        sub = df[[fsi_col, cont_col, mad_col]].dropna()
        if len(sub) == 0:
            return pd.Series(dtype=float)
        codes = (
            np.where(sub[fsi_col] >= t_fsi, "H", "L")
            + np.where(sub[cont_col] >= t_cont, "H", "L")
            + np.where(sub[mad_col] >= t_mad, "H", "L")
        )
        return pd.Series(codes).value_counts(normalize=True)

    sensitivity_rows = []  # for the supplementary LaTeX table
    for axis_label, base, varied_kwarg in [
        ("FSI", BASE_T_FSI, "t_fsi"),
        ("CONT", BASE_T_CONT, "t_cont"),
        ("MAD", BASE_T_MAD, "t_mad"),
    ]:
        kwargs_base = dict(t_fsi=BASE_T_FSI, t_cont=BASE_T_CONT, t_mad=BASE_T_MAD)
        share_lo = _classify_at(**{**kwargs_base, varied_kwarg: base * 0.8})
        share_md = _classify_at(**kwargs_base)
        share_hi = _classify_at(**{**kwargs_base, varied_kwarg: base * 1.2})
        for o in OCTANT_ORDER:
            lo = share_lo.get(o, 0.0) * 100
            md = share_md.get(o, 0.0) * 100
            hi = share_hi.get(o, 0.0) * 100
            sensitivity_rows.append(
                {
                    "axis": axis_label,
                    "octant": o,
                    "lo_pct": lo,
                    "base_pct": md,
                    "hi_pct": hi,
                }
            )
        # Emit max absolute drift across types for this axis. Shares are
        # rounded to the 1-decimal precision displayed in the sensitivity
        # table first, so a reader recomputing the drift from Table values
        # reproduces the quoted maxima exactly.
        def _r(share, o):
            return round(share.get(o, 0.0) * 100, 1)

        max_drift = max(abs(_r(share_lo, o) - _r(share_md, o)) for o in OCTANT_ORDER) if len(share_lo) > 0 else 0
        max_drift_hi = max(abs(_r(share_hi, o) - _r(share_md, o)) for o in OCTANT_ORDER) if len(share_hi) > 0 else 0
        mw.add(f"sensMaxDrift{axis_label}Lo", max_drift, ".1f")
        mw.add(f"sensMaxDrift{axis_label}Hi", max_drift_hi, ".1f")

    # Write the supplementary LaTeX table.
    sens_tex = OUTPUT_DIR / "sensitivity.tex"
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by generate_macros.py — do not edit by hand.",
        "\\begin{tabular}{llrrr}",
        "\\toprule",
        "Axis & Type & $-20\\%$ share (\\%) & Baseline (\\%) & $+20\\%$ share (\\%) \\\\",
        "\\midrule",
    ]
    current_axis = None
    for row in sensitivity_rows:
        axis_disp = row["axis"] if row["axis"] != current_axis else ""
        current_axis = row["axis"]
        lines.append(
            f"{axis_disp} & {row['octant']} & {row['lo_pct']:.1f} & {row['base_pct']:.1f} & {row['hi_pct']:.1f} \\\\"
        )
        if row["octant"] == "LLL" and row != sensitivity_rows[-1]:
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}"]
    sens_tex.write_text("\n".join(lines) + "\n")
    print(f"Wrote sensitivity table to {sens_tex}")

    # ══════════════════════════════════════════════════════════════════
    # Write output
    # ══════════════════════════════════════════════════════════════════
    mw.write(MACRO_FILE)
    print("Done.")


if __name__ == "__main__":
    main()
