#!/usr/bin/env python3
"""Per-column completeness coverage for processed SOAR outputs.

For each city in `boundaries.gpkg`, inspects the processed
`metrics_{bounds_fid}.gpkg.zip` and records the non-null coverage share
for every attribute column in every layer (streets, buildings, blocks).

Outputs:
    paper_data/outputs/completeness_coverage.csv

Examples:
    uv run python paper_data/code/s05_audit_processed_outputs.py
    uv run python paper_data/code/s05_audit_processed_outputs.py --workers 4
"""

from __future__ import annotations

import argparse
import os
import tempfile
import traceback
import zipfile
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

import pandas as pd
import pyogrio
from config import BOUNDS_PATH, PAPER_DIR, PROCESSED_DIR

LAYERS = ("streets", "buildings", "blocks")

# Only report on columns intentionally generated by the SOAR pipeline.
# Upstream metadata columns from Overture, OSM, and Urban Atlas are excluded.
# A column is included if it matches a prefix in the allowlist OR is listed exactly.
_INCLUDE_EXACT: dict[str, set[str]] = {
    "streets": {
        "bounds_fid",
        "ns_node_idx",
        "x",
        "y",
        # demographics
        "t",
        "density",
        "m",
        "m_%",
        "f",
        "f_%",
        "y_lt15",
        "y_lt15_%",
        "y_1564",
        "y_1564_%",
        "y_ge65",
        "y_ge65_%",
        "emp",
        "emp_%",
        "nat",
        "nat_%",
        "eu_oth",
        "eu_oth_%",
        "oth",
        "oth_%",
        "same",
        "same_%",
        "chg_in",
        "chg_in_%",
        "chg_out",
        "chg_out_%",
    },
    "buildings": {
        "bounds_fid",
        "area",
        "perimeter",
        "compactness",
        "orientation",
        "corners",
        "shape_index",
        "fractal_dimension",
        "shared_wall_ratio",
        "shared_walls",
        "mean_height",
        "volume",
        "floor_area",
        "form_factor",
    },
    "blocks": {
        "bounds_fid",
        "block_area",
        "block_perimeter",
        "block_compactness",
        "block_orientation",
        "block_covered_ratio",
        "block_far",
        "block_osr",
        "block_l",
        "block_mean_height",
    },
}
_INCLUDE_PREFIXES: dict[str, tuple[str, ...]] = {
    "streets": ("cc_",),
    "buildings": (),
    "blocks": (),
}


def _is_included(layer: str, col: str) -> bool:
    """Return True if ``col`` is a SOAR-generated column for ``layer``."""
    if col in _INCLUDE_EXACT.get(layer, set()):
        return True
    return any(col.startswith(prefix) for prefix in _INCLUDE_PREFIXES.get(layer, ()))


def _layer_coverage(
    path: Path,
    layer: str,
    bounds_fid: str,
    city_label: str,
    country: str,
) -> list[dict[str, object]]:
    """Compute non-null coverage for every attribute column in a layer."""
    try:
        info = pyogrio.read_info(path, layer=layer)
    except Exception:
        return []
    fields = [f for f in info["fields"] if _is_included(layer, f)]
    n_features = int(info["features"])
    if not fields:
        return []
    if n_features == 0:
        return [
            {
                "bounds_fid": bounds_fid,
                "city_label": city_label,
                "country": country,
                "layer": layer,
                "column": col,
                "n_features": 0,
                "n_nonnull": 0,
                "coverage": 0.0,
            }
            for col in fields
        ]

    parts = ["COUNT(*) AS n_rows"]
    for i, col in enumerate(fields):
        safe = col.replace('"', '""')
        parts.append(f'SUM(CASE WHEN "{safe}" IS NOT NULL THEN 1 ELSE 0 END) AS c{i}')
    sql = f"SELECT {', '.join(parts)} FROM {layer}"
    agg = pyogrio.read_dataframe(path, sql=sql, read_geometry=False).iloc[0]

    rows: list[dict[str, object]] = []
    for i, col in enumerate(fields):
        nn = int(agg[f"c{i}"])
        rows.append(
            {
                "bounds_fid": bounds_fid,
                "city_label": city_label,
                "country": country,
                "layer": layer,
                "column": col,
                "n_features": n_features,
                "n_nonnull": nn,
                "coverage": round(nn / n_features, 6),
            }
        )
    return rows


def _audit_city(task: dict[str, object]) -> list[dict[str, object]]:
    """Return per-column coverage rows for one city.

    Extracts the zipped GeoPackage to a temporary directory before reading:
    GDAL's zip virtual filesystem can deadlock on the large per-column NULL
    aggregation queries when called from multiple worker processes.
    """
    fid = str(task["bounds_fid"])
    zip_path = Path(str(task["metrics_path"]))
    city_label = str(task.get("city_label", ""))
    country = str(task.get("country", ""))

    if not zip_path.exists():
        return []

    rows: list[dict[str, object]] = []
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        try:
            with zipfile.ZipFile(zip_path) as zf:
                zf.extractall(tmp_dir)
        except zipfile.BadZipFile:
            print(f"  Warning: {fid}: bad zip file")
            return []

        gpkgs = list(tmp_dir.glob("*.gpkg"))
        if not gpkgs:
            return []
        gpkg_path = gpkgs[0]

        try:
            available = {name for name, _ in pyogrio.list_layers(gpkg_path)}
        except Exception:
            return []

        for layer in LAYERS:
            if layer in available:
                try:
                    rows.extend(_layer_coverage(gpkg_path, layer, fid, city_label, country))
                except Exception as exc:
                    print(f"  Warning: {fid} {layer}: {type(exc).__name__}: {exc}")
                    traceback.print_exc(limit=1)
    return rows


def _load_tasks(limit: int | None) -> list[dict[str, object]]:
    bounds = pyogrio.read_dataframe(BOUNDS_PATH, columns=["bounds_fid", "label", "country"], read_geometry=False)
    bounds["bounds_fid"] = bounds["bounds_fid"].astype(str)
    tasks = [
        {
            "bounds_fid": row.bounds_fid,
            "city_label": row.label,
            "country": row.country,
            "metrics_path": str(PROCESSED_DIR / f"metrics_{row.bounds_fid}.gpkg.zip"),
        }
        for row in bounds.itertuples(index=False)
    ]
    if limit is not None:
        tasks = tasks[:limit]
    return tasks


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workers", type=int, default=1, help="Number of worker processes.")
    parser.add_argument("--limit", type=int, default=None, help="Optional limit for test runs.")
    args = parser.parse_args(argv)

    out_path = PAPER_DIR / "completeness_coverage.csv"
    if out_path.exists() and args.limit is None:
        print(f"✓ Audit output already exists, skipping: {out_path}")
        return 0

    tasks = _load_tasks(args.limit)
    total = len(tasks)
    print(f"Auditing {total} cities (workers={args.workers})")

    all_rows: list[dict[str, object]] = []
    completed = 0

    if args.workers <= 1:
        for task in tasks:
            all_rows.extend(_audit_city(task))
            completed += 1
            if completed % 25 == 0:
                print(f"  {completed}/{total}")
    else:
        max_workers = min(args.workers, max(1, os.cpu_count() or 1))
        with ProcessPoolExecutor(max_workers=max_workers) as executor:
            future_map = {executor.submit(_audit_city, t): t for t in tasks}
            for future in as_completed(future_map):
                try:
                    all_rows.extend(future.result())
                except Exception as exc:
                    task = future_map[future]
                    print(f"  Error: {task['bounds_fid']}: {exc}")
                completed += 1
                if completed % 25 == 0:
                    print(f"  {completed}/{total}")

    if not all_rows:
        print("No coverage data collected.")
        return 1

    df = pd.DataFrame(all_rows).sort_values(["country", "city_label", "layer", "column"])
    df.to_csv(out_path, index=False)

    n_cities = df["bounds_fid"].nunique()
    n_cols = df.groupby(["layer", "column"]).ngroups
    print(f"Done: {len(df)} rows, {n_cities} cities, {n_cols} unique layer-columns")
    print(f"Wrote: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
